### ISSUE TITLE
Add screenshots to the README.md file

### ISSUE THREAD

**Issue by archit-p** [archpndy/cheer-gh-pages#1]
Currently the readme doesn't contain any pictures. Add screen shots of the running site, to make the readme more descriptive.

**Comment by sdhutchins** [comment]
@archit-p Is there currently a demo? I'd be willing to take a stab at it for you.

**Comment by archit-p** [comment]
@sdhutchins Go ahead and fork the repo, then clone it and use jekyll serve to see the preview. Add screenshots of those pages

**Comment by sdhutchins** [comment]
Awesome. I'm on it.

**Comment by Priyansh2** [comment]
@archit-p is this issue still open ?
